const types = {
  READ_USER_REQUEST: '@user/READ_USER_REQUEST',
  READ_USER_SUCCESS: '@user/READ_USER_SUCCESS',
  SET_USER_LOCATION: '@user/SET_USER_LOCATION',
  GET_DISTANCE_FOR_ENTERPRISE: '@user/GET_DISTANCE_FOR_ENTERPRISE',
};

export default types;
